[versions]
assertj = "3.27.6"
awaitility = "4.3.0"
aws = "2.38.2"
azure-storage-blob = "12.32.0"
bouncycastle = "1.82"
dsp-tck = "1.0.0-RC5"
edc = "0.14.1"
jose4j = "0.9.6"
junit-jupiter = "6.0.1"
kafka = "4.1.0"
keycloak = "26.0.7"
logging-house-client = "1.0.0"
mockito = "5.20.0"
mockserver = "5.15.0"
postgres = "42.7.8"
rest-assured = "5.5.6"
swagger = "2.2.40"
testcontainers = "1.21.3"
testcontainers-keycloak = "3.9.0"
tractusx-edc = "0.11.0"
yasson = "3.0.4"

[libraries]
edc-asset-spi = { module = "org.eclipse.edc:asset-spi", version.ref = "edc" }
edc-core-spi = { module = "org.eclipse.edc:core-spi", version.ref = "edc" }
edc-boot-lib = { module = "org.eclipse.edc:boot-lib", version.ref = "edc" }
edc-catalog-spi = { module = "org.eclipse.edc:catalog-spi", version.ref = "edc" }
edc-contract-spi = { module = "org.eclipse.edc:contract-spi", version.ref = "edc" }
edc-control-plane-spi = { module = "org.eclipse.edc:control-plane-spi", version.ref = "edc" }
edc-controlplane-base-bom = { module = "org.eclipse.edc:controlplane-base-bom", version.ref = "edc" }
edc-controlplane-feature-sql-bom = { module = "org.eclipse.edc:controlplane-feature-sql-bom", version.ref = "edc" }
edc-data-plane-spi = { module = "org.eclipse.edc:data-plane-spi", version.ref = "edc" }
edc-data-plane-http-spi = { module = "org.eclipse.edc:data-plane-http-spi", version.ref = "edc" }
edc-data-plane-public-api-v2 = { module = "org.eclipse.edc:data-plane-public-api-v2", version.ref = "edc" }
edc-data-plane-selector-spi = { module = "org.eclipse.edc:data-plane-selector-spi", version.ref = "edc" }
edc-dataplane-base-bom = { module = "org.eclipse.edc:dataplane-base-bom", version.ref = "edc" }
edc-dataplane-feature-sql-bom = { module = "org.eclipse.edc:dataplane-feature-sql-bom", version.ref = "edc" }
edc-edr-store-spi = { module = "org.eclipse.edc:edr-store-spi", version.ref = "edc" }
edc-http-lib = { module = "org.eclipse.edc:http-lib", version.ref = "edc" }
edc-http-spi = { module = "org.eclipse.edc:http-spi", version.ref = "edc" }
edc-iam-mock = { module = "org.eclipse.edc:iam-mock", version.ref = "edc" }
edc-json-ld-spi = { module = "org.eclipse.edc:json-ld-spi", version.ref = "edc" }
edc-json-ld-lib = { module = "org.eclipse.edc:json-ld-lib", version.ref = "edc" }
edc-junit = { module = "org.eclipse.edc:junit", version.ref = "edc" }
edc-jwt-spi = { module = "org.eclipse.edc:jwt-spi", version.ref = "edc" }
edc-jwt-signer-spi = { module = "org.eclipse.edc:jwt-signer-spi", version.ref = "edc" }
edc-management-api-test-fixtures = { module = "org.eclipse.edc:management-api-test-fixtures", version.ref = "edc" }
edc-oauth2-spi = { module = "org.eclipse.edc:oauth2-spi", version.ref = "edc" }
edc-participant-spi = { module = "org.eclipse.edc:participant-spi", version.ref = "edc" }
edc-policy-spi = { module = "org.eclipse.edc:policy-spi", version.ref = "edc" }
edc-policy-engine-spi = { module = "org.eclipse.edc:policy-engine-spi", version.ref = "edc" }
edc-protocol-spi = { module = "org.eclipse.edc:protocol-spi", version.ref = "edc" }
edc-tck-extension = { module = "org.eclipse.edc:tck-extension", version.ref = "edc" }
edc-token-lib = { module = "org.eclipse.edc:token-lib", version.ref = "edc" }
edc-token-spi = { module = "org.eclipse.edc:token-spi", version.ref = "edc" }
edc-transaction-spi = { module = "org.eclipse.edc:transaction-spi", version.ref = "edc" }
edc-transform-spi = { module = "org.eclipse.edc:transform-spi", version.ref = "edc" }
edc-util-lib = { module = "org.eclipse.edc:util-lib", version.ref = "edc" }
edc-vault-hashicorp = { module = "org.eclipse.edc:vault-hashicorp", version.ref = "edc" }
edc-validator-spi = { module = "org.eclipse.edc:validator-spi", version.ref = "edc" }
edc-validator-lib = { module = "org.eclipse.edc:validator-lib", version.ref = "edc" }
edc-web-spi = { module = "org.eclipse.edc:web-spi", version.ref = "edc" }

edc-aws-data-plane-aws-s3 = { module = "org.eclipse.edc.aws:data-plane-aws-s3", version.ref = "edc" }
edc-aws-validator-data-address-s3 = { module = "org.eclipse.edc.aws:validator-data-address-s3", version.ref = "edc" }

edc-azure-data-plane-azure-storage = { module = "org.eclipse.edc.azure:data-plane-azure-storage", version.ref = "edc" }

tractusx-edc-core-spi = { module = "org.eclipse.tractusx.edc:core-spi", version.ref = "tractusx-edc" }
tractusx-edc-control-plane-migration = { module = "org.eclipse.tractusx.edc:control-plane-migration", version.ref = "tractusx-edc" }
tractusx-edc-data-plane-migration = { module = "org.eclipse.tractusx.edc:data-plane-migration", version.ref = "tractusx-edc" }
tractusx-edc-postgresql-migration = { module = "org.eclipse.tractusx.edc:postgresql-migration-lib", version.ref = "tractusx-edc" }
tractusx-edc-retirement-evaluation-api = { module = "org.eclipse.tractusx.edc:retirement-evaluation-api", version.ref = "tractusx-edc" }
tractusx-edc-retirement-evaluation-core = { module = "org.eclipse.tractusx.edc:retirement-evaluation-core", version.ref = "tractusx-edc" }
tractusx-edc-retirement-evaluation-store-sql = { module = "org.eclipse.tractusx.edc:retirement-evaluation-store-sql", version.ref = "tractusx-edc" }
tractusx-edc-retirement-evaluation-spi = { module = "org.eclipse.tractusx.edc:retirement-evaluation-spi", version.ref = "tractusx-edc" }

logging-house-client = { module = "mds-logging-house:client", version.ref = "logging-house-client" }

assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
aws-iam = { module = "software.amazon.awssdk:iam", version.ref = "aws" }
aws-s3 = { module = "software.amazon.awssdk:s3", version.ref = "aws" }
azure-storage-blob = { group = "com.azure", name = "azure-storage-blob", version.ref = "azure-storage-blob" }
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
dsp-tck-boot = { module = "org.eclipse.dataspacetck.dsp:boot", version.ref = "dsp-tck" }
dsp-tck-core = { module = "org.eclipse.dataspacetck.dsp:core", version.ref = "dsp-tck" }
dsp-tck-runtime = { module = "org.eclipse.dataspacetck.dsp:tck-runtime", version.ref = "dsp-tck" }
dsp-tck-metadata = { module = "org.eclipse.dataspacetck.dsp:dsp-metadata", version.ref = "dsp-tck" }
dsp-tck-catalog = { module = "org.eclipse.dataspacetck.dsp:dsp-catalog", version.ref = "dsp-tck" }
dsp-tck-contract-negotiation = { module = "org.eclipse.dataspacetck.dsp:dsp-contract-negotiation", version.ref = "dsp-tck" }
dsp-tck-transfer-process = { module = "org.eclipse.dataspacetck.dsp:dsp-transfer-process", version.ref = "dsp-tck" }
dsp-tck-system = { module = "org.eclipse.dataspacetck.dsp:dsp-system", version.ref = "dsp-tck" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
keycloak-admin-client = { module = "org.keycloak:keycloak-admin-client", version.ref = "keycloak" }
jose4j = { module = "org.bitbucket.b_c:jose4j", version.ref = "jose4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockserver-netty = { module = "org.mock-server:mockserver-netty", version.ref = "mockserver" }
parsson = { module = "org.eclipse.parsson:parsson", version = "1.1.7" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swagger" }
swagger-jaxrs2-jakarta = { module = "io.swagger.core.v3:swagger-jaxrs2-jakarta", version.ref = "swagger" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers" }
testcontainers-keycloak = { module = "com.github.dasniko:testcontainers-keycloak", version.ref = "testcontainers-keycloak" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-localstack = { module = "org.testcontainers:localstack", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-vault = { module = "org.testcontainers:vault", version.ref = "testcontainers" }
yasson = { module = "org.eclipse:yasson", version.ref = "yasson" }

[plugins]
openapi-generator = { id = "org.openapi.generator", version = "7.17.0" }
swagger = { id = "io.swagger.core.v3.swagger-gradle-plugin", version.ref = "swagger" }
